# -*- coding: utf-8 -*-
"""Deque.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fYE1uwKS2NGxIIMa5PcH4PE4TihATCjG

# Deques 


Unlike stack and queue, the deque (pronounced 'deck') has very few restrictions. 

A **deque**, also known as a **double-ended queue**, is a  collection of items similar to the queue. It has two ends, a front and a _tail.

New items can be added at either the front or the _tail.
Likewise, existing items can be removed from either end. 

In a sense, this hybrid linear structure provides all the capabilities of stacks and queues in a single data structure. 

## The Deque Abstract Data Type

The **deque** abstract data type is defined by the following structure and operations. 

A deque is a collection of items where items are added and
removed from either end, either front or _tail. The deque operations are given below:

- Deque() creates a new deque that is empty. It needs no parameters and returns an empty deque.

- addFirst(item) adds a new item to the front of the deque. It returns nothing.

- addLast(item): adds a new item to the _tail of the deque. It returns
nothing.

- removeFirst(): removes the front item from the deque. The deque is modified. It returns the item. 

- removeLast(): removes the _tail item from the deque. It returns the item. The deque is modified.

- isEmpty(): returns True if the deque is empty, False otherwise.

- _size(): returns the number of items in the deque.

## Implementing a Deque using Python list

Our implementation assumes that the front of the deque is at position 0 in the list
"""

class Deque:
  
  def __init__(self):
    """Create an empty deque"""
    self.items=[]
    
  def addFirst(self,e):
    """Add at the beginning of the deque"""
    self.items.insert(0,e)
    
  def addLast(self,e):
    """Add at the _tail of the deque"""
    self.items.append(e)
    
  def removeFirst(self):
    """Remove and return the first element in the deque"""
    if self.isEmpty():
      print('Error: Deque is empty')
      return None
    #remove first item from the list
    return self.items.pop(0) 
  
  def removeLast(self):
    """Remove and return the element at the _tail of the deque"""
    if self.isEmpty():
      print('Error: Deque is empty')
      return None
    #remove last item from the list
    return self.items.pop() 
  
  def __len__(self):
    """Return the number of elements in the deque"""
    return len(self.items)
  
  def isEmpty(self):
    """Return True if the deque is empty"""
    return len(self)==0
  
  def __str__(self):
    return str(self.items)
  
  
q=Deque()
print('isEmpty()',q.isEmpty())
q.addLast(4)
q.addLast(5)
q.addFirst(3)
q.addFirst(2)
q.addFirst(1)
print('Content of queue:',str(q))
print('isEmpty()',q.isEmpty())
print('removeFirst():',q.removeFirst())
print('removeLast():',q.removeLast())
print('Content of queue:',str(q))
print('_size:',len(q))